apiVersion: v1
kind: Service
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1812
      targetPort: auth-udp
      protocol: UDP
      name: auth-udp
    - port: 1813
      targetPort: acct-udp
      protocol: UDP
      name: acct-udp
  selector:
    {{- include "freeradius.selectorLabels" . | nindent 4 }}
